version: '3'
services:
  database:
    image: postgres:14-alpine
    env_file: vars.env
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      retries: 5

  db-init:
    image: python:3.9-slim
    env_file: vars.env
    volumes:
      - ./sources/b2b/:/b2b
    entrypoint:
      - bash
      - -xc
      - |-
        pip install -r /b2b/script/requirements.txt
        python /b2b/script/seed_db.py
    depends_on:
      database:
        condition: service_healthy

  weblog:
    image: python:3.9-slim
    volumes:
      - ./sources/weblog/script:/script
      - ~/apache-logs:/logs
    entrypoint:
      - bash
      - -xc
      - |-
        pip install -r /script/requirements.txt
        python /script/generate_traces.py
